//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.2.0
//     from Assets/Dean's Stuff/Inputs/DeanControls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @DeanControls : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @DeanControls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""DeanControls"",
    ""maps"": [
        {
            ""name"": ""Debug"",
            ""id"": ""50ceb4ff-8654-472f-96af-442e8fc295e7"",
            ""actions"": [
                {
                    ""name"": ""AI_Move"",
                    ""type"": ""Button"",
                    ""id"": ""ff33d816-42c4-448e-a0bb-6a8c53e6b669"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""AI_Combat"",
                    ""type"": ""Button"",
                    ""id"": ""b9a11369-c3d4-4667-9057-926c3f104439"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Menu"",
                    ""type"": ""Button"",
                    ""id"": ""e5931e43-2df2-4119-9943-569001121430"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""L_Arrow"",
                    ""type"": ""Button"",
                    ""id"": ""11a98b12-581f-4b9f-ae37-f4f38bbb707c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""R_Arrow"",
                    ""type"": ""Button"",
                    ""id"": ""3e60b028-fe21-41bf-8fa3-3254813376d7"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Down_Arrow"",
                    ""type"": ""Button"",
                    ""id"": ""d48f31c0-54a8-4424-a460-74a2e4e6a694"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Up_Arrow"",
                    ""type"": ""Button"",
                    ""id"": ""0972756d-701a-4d9c-b1a5-32d99815f700"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""2a45a5b2-cafe-4ad2-a60e-92ff9cc49318"",
                    ""path"": ""<Keyboard>/o"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AI_Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f57a6872-13a9-4142-870b-ceb051ff27ed"",
                    ""path"": ""<Keyboard>/p"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AI_Combat"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3af5534d-27e0-425f-bfe1-01544207d507"",
                    ""path"": ""<Keyboard>/f12"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Menu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""357f9d1c-6f92-4d02-912e-caaa55f604e1"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""L_Arrow"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5f19a9e0-7004-496c-9434-7cf23d7c231c"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""R_Arrow"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ebcb18e7-48a1-4d3a-8287-b3ce7749b440"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Down_Arrow"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e32ac4c5-4144-4779-a3b0-77020ac4e482"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Up_Arrow"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""PlayerControls"",
            ""id"": ""97d4972b-d29d-4e7e-9864-4a9e69cb1b88"",
            ""actions"": [
                {
                    ""name"": ""MovePlayer"",
                    ""type"": ""PassThrough"",
                    ""id"": ""e3ab5a2f-843a-48cc-a588-f410ffd572d5"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LeftClick"",
                    ""type"": ""Button"",
                    ""id"": ""fa858b31-7b16-4767-9738-90e72728ec79"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""WASD"",
                    ""id"": ""8ebc6ec5-615d-4982-be9d-963d13cf12b2"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MovePlayer"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""ad6078db-0a3e-4d09-b763-d078d29c79c6"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MovePlayer"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""3a51d953-abea-457c-a4de-65b4271ba6b1"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MovePlayer"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""ee6bdb36-7d35-491e-a992-e3b0f46182b6"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MovePlayer"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""0f9b3c17-92c5-4118-a2c5-44d114018f2c"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MovePlayer"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""6b88a829-1b1b-41a9-97d1-5b56ba8eccc6"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftClick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Debug
        m_Debug = asset.FindActionMap("Debug", throwIfNotFound: true);
        m_Debug_AI_Move = m_Debug.FindAction("AI_Move", throwIfNotFound: true);
        m_Debug_AI_Combat = m_Debug.FindAction("AI_Combat", throwIfNotFound: true);
        m_Debug_Menu = m_Debug.FindAction("Menu", throwIfNotFound: true);
        m_Debug_L_Arrow = m_Debug.FindAction("L_Arrow", throwIfNotFound: true);
        m_Debug_R_Arrow = m_Debug.FindAction("R_Arrow", throwIfNotFound: true);
        m_Debug_Down_Arrow = m_Debug.FindAction("Down_Arrow", throwIfNotFound: true);
        m_Debug_Up_Arrow = m_Debug.FindAction("Up_Arrow", throwIfNotFound: true);
        // PlayerControls
        m_PlayerControls = asset.FindActionMap("PlayerControls", throwIfNotFound: true);
        m_PlayerControls_MovePlayer = m_PlayerControls.FindAction("MovePlayer", throwIfNotFound: true);
        m_PlayerControls_LeftClick = m_PlayerControls.FindAction("LeftClick", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Debug
    private readonly InputActionMap m_Debug;
    private IDebugActions m_DebugActionsCallbackInterface;
    private readonly InputAction m_Debug_AI_Move;
    private readonly InputAction m_Debug_AI_Combat;
    private readonly InputAction m_Debug_Menu;
    private readonly InputAction m_Debug_L_Arrow;
    private readonly InputAction m_Debug_R_Arrow;
    private readonly InputAction m_Debug_Down_Arrow;
    private readonly InputAction m_Debug_Up_Arrow;
    public struct DebugActions
    {
        private @DeanControls m_Wrapper;
        public DebugActions(@DeanControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @AI_Move => m_Wrapper.m_Debug_AI_Move;
        public InputAction @AI_Combat => m_Wrapper.m_Debug_AI_Combat;
        public InputAction @Menu => m_Wrapper.m_Debug_Menu;
        public InputAction @L_Arrow => m_Wrapper.m_Debug_L_Arrow;
        public InputAction @R_Arrow => m_Wrapper.m_Debug_R_Arrow;
        public InputAction @Down_Arrow => m_Wrapper.m_Debug_Down_Arrow;
        public InputAction @Up_Arrow => m_Wrapper.m_Debug_Up_Arrow;
        public InputActionMap Get() { return m_Wrapper.m_Debug; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(DebugActions set) { return set.Get(); }
        public void SetCallbacks(IDebugActions instance)
        {
            if (m_Wrapper.m_DebugActionsCallbackInterface != null)
            {
                @AI_Move.started -= m_Wrapper.m_DebugActionsCallbackInterface.OnAI_Move;
                @AI_Move.performed -= m_Wrapper.m_DebugActionsCallbackInterface.OnAI_Move;
                @AI_Move.canceled -= m_Wrapper.m_DebugActionsCallbackInterface.OnAI_Move;
                @AI_Combat.started -= m_Wrapper.m_DebugActionsCallbackInterface.OnAI_Combat;
                @AI_Combat.performed -= m_Wrapper.m_DebugActionsCallbackInterface.OnAI_Combat;
                @AI_Combat.canceled -= m_Wrapper.m_DebugActionsCallbackInterface.OnAI_Combat;
                @Menu.started -= m_Wrapper.m_DebugActionsCallbackInterface.OnMenu;
                @Menu.performed -= m_Wrapper.m_DebugActionsCallbackInterface.OnMenu;
                @Menu.canceled -= m_Wrapper.m_DebugActionsCallbackInterface.OnMenu;
                @L_Arrow.started -= m_Wrapper.m_DebugActionsCallbackInterface.OnL_Arrow;
                @L_Arrow.performed -= m_Wrapper.m_DebugActionsCallbackInterface.OnL_Arrow;
                @L_Arrow.canceled -= m_Wrapper.m_DebugActionsCallbackInterface.OnL_Arrow;
                @R_Arrow.started -= m_Wrapper.m_DebugActionsCallbackInterface.OnR_Arrow;
                @R_Arrow.performed -= m_Wrapper.m_DebugActionsCallbackInterface.OnR_Arrow;
                @R_Arrow.canceled -= m_Wrapper.m_DebugActionsCallbackInterface.OnR_Arrow;
                @Down_Arrow.started -= m_Wrapper.m_DebugActionsCallbackInterface.OnDown_Arrow;
                @Down_Arrow.performed -= m_Wrapper.m_DebugActionsCallbackInterface.OnDown_Arrow;
                @Down_Arrow.canceled -= m_Wrapper.m_DebugActionsCallbackInterface.OnDown_Arrow;
                @Up_Arrow.started -= m_Wrapper.m_DebugActionsCallbackInterface.OnUp_Arrow;
                @Up_Arrow.performed -= m_Wrapper.m_DebugActionsCallbackInterface.OnUp_Arrow;
                @Up_Arrow.canceled -= m_Wrapper.m_DebugActionsCallbackInterface.OnUp_Arrow;
            }
            m_Wrapper.m_DebugActionsCallbackInterface = instance;
            if (instance != null)
            {
                @AI_Move.started += instance.OnAI_Move;
                @AI_Move.performed += instance.OnAI_Move;
                @AI_Move.canceled += instance.OnAI_Move;
                @AI_Combat.started += instance.OnAI_Combat;
                @AI_Combat.performed += instance.OnAI_Combat;
                @AI_Combat.canceled += instance.OnAI_Combat;
                @Menu.started += instance.OnMenu;
                @Menu.performed += instance.OnMenu;
                @Menu.canceled += instance.OnMenu;
                @L_Arrow.started += instance.OnL_Arrow;
                @L_Arrow.performed += instance.OnL_Arrow;
                @L_Arrow.canceled += instance.OnL_Arrow;
                @R_Arrow.started += instance.OnR_Arrow;
                @R_Arrow.performed += instance.OnR_Arrow;
                @R_Arrow.canceled += instance.OnR_Arrow;
                @Down_Arrow.started += instance.OnDown_Arrow;
                @Down_Arrow.performed += instance.OnDown_Arrow;
                @Down_Arrow.canceled += instance.OnDown_Arrow;
                @Up_Arrow.started += instance.OnUp_Arrow;
                @Up_Arrow.performed += instance.OnUp_Arrow;
                @Up_Arrow.canceled += instance.OnUp_Arrow;
            }
        }
    }
    public DebugActions @Debug => new DebugActions(this);

    // PlayerControls
    private readonly InputActionMap m_PlayerControls;
    private IPlayerControlsActions m_PlayerControlsActionsCallbackInterface;
    private readonly InputAction m_PlayerControls_MovePlayer;
    private readonly InputAction m_PlayerControls_LeftClick;
    public struct PlayerControlsActions
    {
        private @DeanControls m_Wrapper;
        public PlayerControlsActions(@DeanControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @MovePlayer => m_Wrapper.m_PlayerControls_MovePlayer;
        public InputAction @LeftClick => m_Wrapper.m_PlayerControls_LeftClick;
        public InputActionMap Get() { return m_Wrapper.m_PlayerControls; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerControlsActions set) { return set.Get(); }
        public void SetCallbacks(IPlayerControlsActions instance)
        {
            if (m_Wrapper.m_PlayerControlsActionsCallbackInterface != null)
            {
                @MovePlayer.started -= m_Wrapper.m_PlayerControlsActionsCallbackInterface.OnMovePlayer;
                @MovePlayer.performed -= m_Wrapper.m_PlayerControlsActionsCallbackInterface.OnMovePlayer;
                @MovePlayer.canceled -= m_Wrapper.m_PlayerControlsActionsCallbackInterface.OnMovePlayer;
                @LeftClick.started -= m_Wrapper.m_PlayerControlsActionsCallbackInterface.OnLeftClick;
                @LeftClick.performed -= m_Wrapper.m_PlayerControlsActionsCallbackInterface.OnLeftClick;
                @LeftClick.canceled -= m_Wrapper.m_PlayerControlsActionsCallbackInterface.OnLeftClick;
            }
            m_Wrapper.m_PlayerControlsActionsCallbackInterface = instance;
            if (instance != null)
            {
                @MovePlayer.started += instance.OnMovePlayer;
                @MovePlayer.performed += instance.OnMovePlayer;
                @MovePlayer.canceled += instance.OnMovePlayer;
                @LeftClick.started += instance.OnLeftClick;
                @LeftClick.performed += instance.OnLeftClick;
                @LeftClick.canceled += instance.OnLeftClick;
            }
        }
    }
    public PlayerControlsActions @PlayerControls => new PlayerControlsActions(this);
    public interface IDebugActions
    {
        void OnAI_Move(InputAction.CallbackContext context);
        void OnAI_Combat(InputAction.CallbackContext context);
        void OnMenu(InputAction.CallbackContext context);
        void OnL_Arrow(InputAction.CallbackContext context);
        void OnR_Arrow(InputAction.CallbackContext context);
        void OnDown_Arrow(InputAction.CallbackContext context);
        void OnUp_Arrow(InputAction.CallbackContext context);
    }
    public interface IPlayerControlsActions
    {
        void OnMovePlayer(InputAction.CallbackContext context);
        void OnLeftClick(InputAction.CallbackContext context);
    }
}
